### ISSUE TITLE
missing libicu and webp

### ISSUE THREAD

**Issue by Red-Eyed** [flathub/io.qt.qtwebkit.BaseApp#22]
Hello, just wanted to create teamviewer recipe, and faced out with missing libraries
```
	libicuuc.so.57 => not found
	libicui18n.so.57 => not found
	libwebp.so.6 => not found
```
it seems that `libicuuc` and `libwebp` is a [QtWebKit dependency](https://github.com/qtwebkit/qtwebkit/wiki/Building-QtWebKit-on-Linux)

**Comment by barthalion** [comment]
Which runtime are you using and which branch of the BaseApp? Both libicu and libwebp are available in the runtime.

**Comment by Red-Eyed** [comment]
Hello, I'm newbie to `flatpak-build`
trying to build it using this yml
```yml
app-id: com.teamviewer.TeamViewer
base: io.qt.qtwebkit.BaseApp
base-version: stable
runtime: org.kde.Platform
runtime-version: "5.14"
sdk: org.kde.Sdk
command: teamviewer
separate-locales: false
tags:
  - proprietary
finish-args:
  - "--share=ipc"
  - "--socket=x11"
  - "--socket=wayland"
  - "--socket=pulseaudio"
  - "--share=network"
  - "--device=all"
  - "--filesystem=home"
  - "--allow=devel"
cleanup-commands:
  - mkdir -p /app/lib/ffmpeg
modules:
  - name: teamviewer
    buildsystem: simple
    build-commands:
      - install -Dm755 apply_extra /app/bin/apply_extra
      - install -Dm755 teamviewer.sh /app/bin/teamviewer
    sources:
      - type: script
        dest-filename: apply_extra
        commands:
          - tar xf teamviewer.tar.xz
          - rm -f teamviewer.tar.xz
          - mv teamviewer teamviewer-29c0
          - mv teamviewer-29c0/* .
          - chmod -R a-s,go+rX,go-w .
          - rmdir teamviewer-29c0
          - mkdir -p export/share/applications
          - sed 's|Icon=TeamViewer|Icon=com.teamviewer.TeamViewer|; s|Exec=/opt/teamviewer/tv_bin/script/teamviewer|Exec=teamviewer|'
            tv_bin/desktop/com.teamviewer.TeamViewer.desktop > export/share/applications/com.teamviewer.TeamViewer.desktop
          - mkdir -p export/share/icons/hicolor/256x256/apps
          - cp tv_bin/desktop/teamviewer_256.png export/share/icons/hicolor/256x256/apps/com.teamviewer.TeamViewer.png
      - type: script
        dest-filename: teamviewer.sh
        commands:
          - ls -la /app/lib/
          - ldd /app/extra/tv_bin/TeamViewer
          - exec /app/extra/teamviewer "$@"
      - type: extra-data
        filename: teamviewer.tar.xz
        only-arches:
          - x86_64
        url: https://download.teamviewer.com/download/linux/teamviewer_amd64.tar.xz
        sha256: fa4b47bea5ae061ba6b1003d2284b68239b579c2f2098a7798c54d5f93b870fa
        size: 13056296
      - type: extra-data
        filename: teamviewer.tar.xz
        only-arches:
          - i386
        url: https://download.teamviewer.com/download/linux/teamviewer_i386.tar.xz
        sha256: 89b1d1ff9ba6ca7834e561068a255ba1ea3987f661ffdbe3a09b74d09f5d1bf4
        size: 13631276
```

and this commands:  
1. `flatpak-builder build-dir com.teamviewer.TeamViewer.yml --install --user --verbose --force-clean`  
2. `flatpak run com.teamviewer.TeamViewer`
